# Reading CSV Files

A CSV (Comma-Separated Values) file is a plain text file that stores tabular data, with each line representing a row and commas separating the columns

In [1]:
import pandas as pd

In [2]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
file_path = '/content/drive/MyDrive/ML_practice_datasets/student_performance_dataset.csv'

In [4]:
# Import the data
data = pd.read_csv(file_path)

In [5]:
print(data.head(5))

   student_id  gender  study_time_hours  attendance_percent  sleep_hours  \
0           1    Male               4.0                98.0          6.5
1           2  Female               6.3               100.0          5.7
2           3    Male               4.9                85.3          7.9
3           4    Male               2.6                77.5          8.0
4           5    Male               2.2                89.6          4.6

  parental_education internet_access extracurricular_activities part_time_job  \
0          Bachelors             Yes                        Yes            No
1        High School             Yes                        Yes           Yes
2          Bachelors             Yes                         No           Yes
3                NaN             Yes                        Yes            No
4          Bachelors             Yes                         No           Yes

   previous_grade  final_exam_score final_grade
0            76.9             100.0           A
1            75.5             100.0           A
2            88.5              97.3           A
3            85.1              83.8           B
4            61.8              68.3           D

In [6]:
data.final_exam_score[:5]

0    100.0
1    100.0
2     97.3
3     83.8
4     68.3
Name: final_exam_score, dtype: float64

In [7]:
# Skip 1st row, headers(column names), and set no headers
data = pd.read_csv(file_path, header=None, skiprows=1)
data.head(3)

   0       1    2      3    4            5    6    7    8     9      10 11
0   1    Male  4.0   98.0  6.5    Bachelors  Yes  Yes   No  76.9  100.0  A
1   2  Female  6.3  100.0  5.7  High School  Yes  Yes  Yes  75.5  100.0  A
2   3    Male  4.9   85.3  7.9    Bachelors  Yes   No  Yes  88.5   97.3  A

In [8]:
# skip the 1st row and Provide custom names for the columns
data = pd.read_csv(file_path, skiprows=1 ,names=["id", "sex", "std_t", "attd_p", "sleep_h", "lvl", "web_acc", "extra", "ptj", "lst_grd", "f_scr", "grd"])
data.head(3)

,id,sex,std_t,attd_p,sleep_h,lvl,web_acc,extra,ptj,lst_grd,f_scr,grd
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A

In [24]:
# Load only specific columns names
data = pd.read_csv(file_path, usecols=['parental_education', 'final_exam_score'])
data.head(3)

  parental_education  final_exam_score
0          Bachelors             100.0
1        High School             100.0
2          Bachelors              97.3

In [27]:
# Check missing values
data = pd.read_csv(file_path)
# Returns the total count of NA values for each column
data.isna().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [29]:
data = pd.read_csv(file_path)
print(f"len(data): {len(data)}")
# Drops the row if any column in that row contains an NA
data_clean = data.dropna()
print(f"len(data_clean): {len(data_clean)}")

len(data): 1000
len(data_clean): 898

### Different delimiters - tab-separated file (.tsv)

```py
data = pd.read_csv(file_path, sep="\t")
```

### Different delimiters - space-separated file

```py
data = pd.read_csv(filepath, delim_whitespace=True)
```

------------------------------------------

| <img src="https://github.com/madhawapolkotuwa.png" width="80" style="border-radius: 50%;"> | **MPCoding**<br>*Machine Learning Tutorial Series*<br><br> [![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)](https://www.youtube.com/@MP-Coding) [![GitHub](https://img.shields.io/badge/github-repo-blue?logo=github)](https://github.com/madhawapolkotuwa) |
|---|---|

<p align="left" style="font-size: 0.85em; color: gray; margin-top: 10px;">
  © 2026 MPCoding. Educational materials are free to use with proper attribution.
</p>